### ISSUE TITLE
Game crashing on victory

### ISSUE THREAD

**Issue by rayannott** [deepthi76/Connect-Four#1]
Hi deepthi76.
I checked out your game. I was hoping that "multiplayer" meant different machines exchanging sockets or something, but we have what we have I guess :)
So, when someone wins, I am shown this error message:
`line 228, in screen2 ... NameError: name 'p1' is not defined`
I believe the problem is that the global variable does not get initialized.

**Comment by deepthi76** [comment]
Hi rayannott.
In the first screen, the user needs to press enter/return after entering each name. That's how the global variable gets initialised. I have mentioned that in the game in the latest update. Thank you.
